### ISSUE TITLE
Problem description miss "not" in "Joins with WHERE"

### ISSUE THREAD

**Issue by Sh7ne** [rhc2104/sqlteaching#13]
Can you return a list of characters and TV shows that are not named "Willow Rosenberg" and in the show "How I Met Your Mother"?

should be not in the show "HIMYM"

**Comment by rhc2104** [comment]
Thank you.  It has been fixed here: https://github.com/rhc2104/sqlteaching/commit/903da7d3d21c7d6a15b8b2a163bfe3abc1ff79be
