### ISSUE TITLE
GROUP By

### ISSUE THREAD

**Issue by johnwilson** [rhc2104/sqlteaching#5]
Group By lesson 16 doesn't return expected results.

**Comment by rhc2104** [comment]
Hi @johnwilson , can you be more specific?

The query "SELECT MAX(height_cm), species FROM friends_of_pickles GROUP BY species;" works for me.

**Comment by johnwilson** [comment]
Apologies, I misread the question in my haste. Thanks, great site

**Comment by rhc2104** [comment]
Hi John,

Sorry about the delay.  The case specificity has been fixed.
